services:
  web:
    image: pifive:5001/university:latest
    volumes:
      - /mnt/ssd/@docker/university/db:/var/lib/postgresql
    environment:
      - SESSION_SECRET
    networks:
      - proxy_net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M

networks:
  proxy_net:
    external: true
