import { Injectable } from '@angular/core';
import { Course } from '../models/course.model';

@Injectable({ providedIn: 'root' })
export class CourseService {
  getCourse(): Course {
    return {
      id: 'java-se-25',
      title: 'Java SE 25 Programming Complete',
      tag: 'Course',
      audience: 'All Users',
      moduleCount: 10,
      duration: '40h 17m',
      description:
        'This course on Java SE 25 (latest Long-Term Support release) equips you with the latest tools and knowledge to build secure, efficient, and maintainable applications. It positions you well for career advancement, ensures your skills remain relevant, and allows you to take full advantage of the ongoing improvements in the Java platform.',
      benefits: [
        'Understand Java SE 25 features and object-oriented programming concepts',
        'Work with primitives, operators, control flow, and data structures',
        'Apply OOP principles: inheritance, polymorphism, interfaces, and enums',
        'Handle exceptions and work with the Java I/O API',
        'Process data with streams, lambdas, and the Collections framework',
        'Write concurrent code using threads, executors, and virtual threads',
        'Package and deploy Java applications with the module system',
        'Implement localization using locales and resource bundles',
      ],
      modules: [
        {
          id: 1,
          title: 'Introduction to Java',
          expanded: true,
          lessons: [
            { id: '1-1', title: 'Course Overview', duration: '6m', type: 'video', status: 'new' },
            { id: '1-2', title: 'Java History', duration: '4m', type: 'video', status: 'new' },
            {
              id: '1-3',
              title: 'Explain Java Features and Object-Oriented Concepts',
              duration: '30m',
              type: 'video',
              status: 'new',
            },
            {
              id: '1-4',
              title: 'Define a Java Program',
              duration: '13m',
              type: 'video',
              status: 'new',
            },
            {
              id: '1-5',
              title: 'Compile and Execute your first Java Program',
              duration: '10m',
              type: 'video',
              status: 'new',
            },
            {
              id: '1-6',
              title: 'Code snippets and Summary',
              duration: '4m',
              type: 'video',
              status: 'new',
            },
            {
              id: '1-7',
              title: 'Practice 1-1: Verify the JDK Installation',
              duration: '5m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '1-8',
              title: 'Practice 1-2: Create, Compile, and Execute a Java Application',
              duration: '10m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '1-9',
              title: 'Skill Check: Introduction to Java',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 2,
          title: 'Handling Date, Time, Text, Numeric and Boolean Values',
          expanded: false,
          lessons: [
            {
              id: '2-1',
              title: 'Primitives and Wrapper Classes',
              duration: '15m',
              type: 'video',
              status: 'new',
            },
            {
              id: '2-2',
              title: 'Arithmetic and Boolean Expressions with Math API',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '2-3',
              title: 'String and StringBuilder Classes',
              duration: '20m',
              type: 'video',
              status: 'new',
            },
            {
              id: '2-4',
              title: 'Text Blocks',
              duration: '12m',
              type: 'video',
              status: 'new',
            },
            {
              id: '2-5',
              title: 'Date-Time API: LocalDate, LocalTime, LocalDateTime',
              duration: '22m',
              type: 'video',
              status: 'new',
            },
            {
              id: '2-6',
              title: 'Duration, Period, Instant and Time Zones',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '2-7',
              title: 'Practice: Date, Time and Text',
              duration: '15m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '2-8',
              title: 'Skill Check: Handling Values',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 3,
          title: 'Implementing Program Flow Control',
          expanded: false,
          lessons: [
            {
              id: '3-1',
              title: 'if/else Statements',
              duration: '12m',
              type: 'video',
              status: 'new',
            },
            {
              id: '3-2',
              title: 'Switch Statements and Expressions',
              duration: '20m',
              type: 'video',
              status: 'new',
            },
            {
              id: '3-3',
              title: 'Loops: for, while, do-while',
              duration: '15m',
              type: 'video',
              status: 'new',
            },
            {
              id: '3-4',
              title: 'Break and Continue Statements',
              duration: '8m',
              type: 'video',
              status: 'new',
            },
            {
              id: '3-5',
              title: 'Practice: Flow Control',
              duration: '12m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '3-6',
              title: 'Skill Check: Flow Control',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 4,
          title: 'Applying Object-Oriented Principles',
          expanded: false,
          lessons: [
            {
              id: '4-1',
              title: 'Object Life-Cycle and Garbage Collection',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-2',
              title: 'Classes, Records, Fields, and Methods',
              duration: '25m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-3',
              title: 'Constructors and Initializers',
              duration: '15m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-4',
              title: 'Overloaded Methods and var-args',
              duration: '12m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-5',
              title: 'Encapsulation, Immutability, var, and Unnamed Variables',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-6',
              title: 'Inheritance, Abstract and Sealed Types',
              duration: '28m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-7',
              title: 'Interfaces and Functional Interfaces',
              duration: '22m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-8',
              title: 'Enum Types',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '4-9',
              title: 'Practice: OOP Principles',
              duration: '20m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '4-10',
              title: 'Skill Check: OOP',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 5,
          title: 'Implementing Exception Handling',
          expanded: false,
          lessons: [
            {
              id: '5-1',
              title: 'try/catch/finally Blocks',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '5-2',
              title: 'try-with-resources',
              duration: '12m',
              type: 'video',
              status: 'new',
            },
            {
              id: '5-3',
              title: 'Multi-catch and Custom Exceptions',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '5-4',
              title: 'Practice: Exception Handling',
              duration: '10m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '5-5',
              title: 'Skill Check: Exceptions',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 6,
          title: 'Using Arrays and Collections',
          expanded: false,
          lessons: [
            {
              id: '6-1',
              title: 'Arrays',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '6-2',
              title: 'List and Set',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '6-3',
              title: 'Map and Deque',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '6-4',
              title: 'Sequenced Collections',
              duration: '10m',
              type: 'video',
              status: 'new',
            },
            {
              id: '6-5',
              title: 'Sorting and Retrieving Elements',
              duration: '12m',
              type: 'video',
              status: 'new',
            },
            {
              id: '6-6',
              title: 'Practice: Collections',
              duration: '15m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '6-7',
              title: 'Skill Check: Collections',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 7,
          title: 'Processing Data with Streams and Lambdas',
          expanded: false,
          lessons: [
            {
              id: '7-1',
              title: 'Lambda Expressions and Functional Interfaces',
              duration: '20m',
              type: 'video',
              status: 'new',
            },
            {
              id: '7-2',
              title: 'Object and Primitive Streams',
              duration: '22m',
              type: 'video',
              status: 'new',
            },
            {
              id: '7-3',
              title: 'Filter, Transform, and Sort',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '7-4',
              title: 'Reduction, Grouping, and Partitioning',
              duration: '20m',
              type: 'video',
              status: 'new',
            },
            {
              id: '7-5',
              title: 'Parallel Streams',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '7-6',
              title: 'Practice: Streams',
              duration: '20m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '7-7',
              title: 'Skill Check: Streams and Lambdas',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 8,
          title: 'Packaging and Deploying Java Code',
          expanded: false,
          lessons: [
            {
              id: '8-1',
              title: 'Module System Overview',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '8-2',
              title: 'Declaring Module Dependencies',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '8-3',
              title: 'Services, Providers, and Consumers',
              duration: '12m',
              type: 'video',
              status: 'new',
            },
            {
              id: '8-4',
              title: 'Compact Source Files and Instance Main Methods',
              duration: '10m',
              type: 'video',
              status: 'new',
            },
            {
              id: '8-5',
              title: 'Creating Modular and Non-modular JARs',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '8-6',
              title: 'Migration to Modules',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '8-7',
              title: 'Practice: Packaging',
              duration: '15m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '8-8',
              title: 'Skill Check: Packaging',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 9,
          title: 'Implementing Multithreading',
          expanded: false,
          lessons: [
            {
              id: '9-1',
              title: 'Platform and Virtual Threads',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '9-2',
              title: 'Runnable, Callable, and Thread Lifecycle',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '9-3',
              title: 'Executor Services and Concurrent API',
              duration: '20m',
              type: 'video',
              status: 'new',
            },
            {
              id: '9-4',
              title: 'Scoped Values',
              duration: '10m',
              type: 'video',
              status: 'new',
            },
            {
              id: '9-5',
              title: 'Thread-safe Code and Locking Mechanisms',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '9-6',
              title: 'Concurrent Collections and Parallel Streams',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '9-7',
              title: 'Practice: Multithreading',
              duration: '20m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '9-8',
              title: 'Skill Check: Multithreading',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
        {
          id: 10,
          title: 'I/O and Localization',
          expanded: false,
          lessons: [
            {
              id: '10-1',
              title: 'Reading and Writing Console and File Data',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '10-2',
              title: 'Serialization and Deserialization',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '10-3',
              title: 'java.nio.file API and Path Objects',
              duration: '18m',
              type: 'video',
              status: 'new',
            },
            {
              id: '10-4',
              title: 'Localization with Locales and Resource Bundles',
              duration: '16m',
              type: 'video',
              status: 'new',
            },
            {
              id: '10-5',
              title: 'Parsing and Formatting Messages, Dates, and Numbers',
              duration: '14m',
              type: 'video',
              status: 'new',
            },
            {
              id: '10-6',
              title: 'Practice: I/O and Localization',
              duration: '15m',
              type: 'practice',
              status: 'new',
            },
            {
              id: '10-7',
              title: 'Skill Check: I/O and Localization',
              duration: '',
              type: 'skill-check',
              status: 'not-attempted',
            },
          ],
        },
      ],
    };
  }
}
